aragon:
  - upTo: 12000
    retention: 9.5
  - upTo: 20200
    retention: 12
  - upTo: 34000
    retention: 15
  - upTo: 50000
    retention: 18.5
  - upTo: 60000
    retention: 20.5
  - upTo: 70000
    retention: 23 
  - upTo: 90000
    retention: 24
  - upTo: 130000
    retention: 25
  - upTo: 150000
    retention: 25.5 
  - upTo: 10000000
    retention: 25    
asturias:
  - upTo: 12450
    retention: 10
  - upTo: 17700
    retention: 12
  - upTo: 33007
    retention: 14
  - upTo: 53407
    retention: 18.5
  - upTo: 70000
    retention: 21.5
  - upTo: 90000
    retention: 22.5 
  - upTo: 175000
    retention: 25
  - upTo: 10000000
    retention: 25.5    