aragon:
  - upTo: 12000
    retention: 9.5
  - upTo: 20200
    retention: 12
  - upTo: 34000
    retention: 15
  - upTo: 50000
    retention: 18.5
  - upTo: 60000
    retention: 20.5
  - upTo: 70000
    retention: 23 
  - upTo: 90000
    retention: 24
  - upTo: 130000
    retention: 25
  - upTo: 150000
    retention: 25.5 
  - upTo: 10000000
    retention: 25    
asturias:
  - upTo: 12450
    retention: 10
  - upTo: 17700
    retention: 12
  - upTo: 33007
    retention: 14
  - upTo: 53407
    retention: 18.5
  - upTo: 70000
    retention: 21.5
  - upTo: 90000
    retention: 22.5 
  - upTo: 175000
    retention: 25
  - upTo: 10000000
    retention: 25.5    
baleares:
  - upTo: 10000
    retention: 9.5
  - upTo: 18000
    retention: 11.75
  - upTo: 30000
    retention: 14.75
  - upTo: 48000
    retention: 17.75
  - upTo: 70000
    retention: 19.5
  - upTo: 90000
    retention: 22
  - upTo: 120000
    retention: 23
  - upTo: 175000
    retention: 24
  - upTo: 1000000
    retention: 25
galicia:
  - upTo: 12985
    retention: 9
  - upTo: 21068
    retention: 11.65
  - upTo: 27700
    retention: 14.9
  - upTo: 35200
    retention: 17
  - upTo: 60000
    retention: 18.5
  - upTo: 10000000
    retention: 22.5
canarias:
  - upTo: 12450
    retention: 9
  - upTo: 17707
    retention: 11.5
  - upTo: 33007
    retention: 14
  - upTo: 53407
    retention: 18.5
  - upTo: 90000
    retention: 23.5
  - upTo: 120000
    retention: 25
  - upTo: 10000000
    retention: 26
madrid:
  - upTo: 12960.45
    retention: 8.5
  - upTo: 18433.19
    retention: 10.7
  - upTo: 34350.49
    retention: 12.8
  - upTo: 55601.89
    retention: 17.4
  - upTo: 10000000
    retention: 20.5
extranjero:
  - upTo: 12450
    retention: 9.5
  - upTo: 20200
    retention: 12
  - upTo: 35200
    retention: 15
  - upTo: 60000
    retention: 18.5
  - upTo: 300000
    retention: 22.5
  - upTo: 1000000
    retention: 24.5
